Repository elixir-error-tracker/error-tracker, pull requests merged in 2024-08, with the labels that each got.

#33 Allow mounting the dashboard without parens
  .formatter.exs
  dev.exs
Labels: enhancement

#36 Fix some exceptions reporting
  lib/error_tracker.ex
  lib/error_tracker/schemas/error.ex
  lib/error_tracker/schemas/stacktrace.ex
  lib/error_tracker/web/live/show.html.heex
Labels: bug

#37 Fix prefix usage in PostgreSQL
  lib/error_tracker/repo.ex
Labels: bug

#38 Telemetry events
  dev.exs
  guides/Getting Started.md
  lib/error_tracker.ex
  lib/error_tracker/repo.ex
  lib/error_tracker/telemetry.ex
Labels: enhancement

#34 Unit tests
  .github/workflows/elixir.yml
  .gitignore
  README.md
  config/config.exs
  config/dev.example.exs
  config/test.example.exs
  dev.exs
  dev.local.example.exs
  lib/error_tracker/integrations/oban.ex
  lib/error_tracker/integrations/phoenix.ex
  lib/error_tracker/migration.ex
  lib/error_tracker/migration/postgres.ex
  lib/error_tracker/migration/sql_migrator.ex
  mix.exs
  priv/repo/migrations/20240527155639_create_error_tracker_tables.exs
  test/error_tracker/telemetry_test.exs
  test/error_tracker_test.exs
  test/support/case.ex
  test/support/lite_repo.ex
  test/support/repo.ex
  test/support/repo/migrations/20240527155639_create_error_tracker_tables.exs
  test/test_helper.exs
Labels: enhancement

#44 Ensure migration_timestamp is a varchar
  lib/error_tracker/migration/sql_migrator.ex
Labels: bug

#68 Update install guides migration example
  guides/Getting Started.md
Labels: documentation

#70 Fix reporting errors from Oban
  lib/error_tracker/integrations/oban.ex
  lib/error_tracker/schemas/error.ex
  lib/error_tracker/web/live/dashboard.html.heex
  lib/error_tracker/web/live/show.html.heex
Labels: bug
